# Generated by Django 6.0.5 on 2026-06-12 11:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('merchant', 'Merchant'), ('lender_partner', 'Lender Partner'), ('compliance', 'Compliance Officer'), ('admin', 'Administrator'), ('support', 'Support Staff')], default='merchant', help_text="User's role determines access permissions", max_length=20)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('business_type', models.CharField(choices=[('retail', 'Retail'), ('food', 'Food'), ('service', 'Service')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tax_id_encrypted', models.TextField(blank=True, help_text='Encrypted Tax ID / SSN', null=True)),
                ('account_number_encrypted', models.TextField(blank=True, help_text='Encrypted Bank Account Number', null=True)),
                ('tax_id_last4', models.CharField(blank=True, help_text='Last 4 digits of tax ID for display purposes', max_length=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this merchant record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_merchants', to=settings.AUTH_USER_MODEL)),
                ('owner', models.OneToOneField(blank=True, help_text='User who owns this merchant account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_merchant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_sensitive_merchant_data', 'Can view encrypted merchant data'), ('export_merchant_data', 'Can export merchant data')],
            },
        ),
        migrations.CreateModel(
            name='FinancingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason if rejected')),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved/rejected this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_financing_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_financing_requests', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('approve_financing_request', 'Can approve financing requests')],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_merchants',
            field=models.ManyToManyField(blank=True, help_text='Merchants assigned to this lender partner', related_name='assigned_lenders', to='api.merchant'),
        ),
        migrations.AddField(
            model_name='user',
            name='merchant_profile',
            field=models.OneToOneField(blank=True, help_text='Link to merchant profile if role is merchant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='api.merchant'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW_SENSITIVE', 'Viewed Sensitive Data'), ('CREATE', 'Created Resource'), ('UPDATE', 'Updated Resource'), ('DELETE', 'Deleted Resource'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('EXPORT', 'Data Export'), ('ROLE_CHANGE', 'Role Changed')], max_length=20)),
                ('resource_type', models.CharField(help_text='Type of resource accessed (Merchant, FinancingRequest, etc.)', max_length=50)),
                ('resource_id', models.IntegerField(help_text='ID of the resource accessed')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/Client information')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional context about the action')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='api_auditlo_timesta_da87a7_idx'), models.Index(fields=['user', 'action'], name='api_auditlo_user_id_c3bd49_idx'), models.Index(fields=['resource_type', 'resource_id'], name='api_auditlo_resourc_c074b3_idx')],
            },
        ),
    ]
