# Generated by Django 6.0.5 on 2026-05-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financingrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
